# Generated by Django 5.0.2 on 2024-03-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
